[tox]
envlist = py310,py313
# Minimum version of tox
minversion = 3.3.0
isolated_build = true

[tool:pytest]
testpaths = tests
log_level = DEBUG
log_cli = true
log_cli_level = DEBUG


[coverage:paths]
source =
   src
   */site-packages


[coverage:run]
branch = true
parallel = true
source =
    restsh

[coverage:report]
show_missing = true
precision = 2

[testenv]
setenv =
    py310: COVERAGE_FILE = .coverage.{envname}
    py313: COVERAGE_FILE = .coverage.{envname}
deps =
    readme_renderer
    pylint
    mypy
    pytest
    pytest-cov
    build
    twine
    types-PyYAML
    types-python-dateutil
    amqp
commands =
    pylint restsh
    mypy -p src.restsh
    python -m build
	python -m twine check dist/*


